[workspace]
resolver = "2"

members = [
    "rosenpass",
    "ciphers",
    "util",
    "constant-time",
    "sodium",
    "to",
    "fuzzing",
]

[workspace.metadata.release]
# ensure that adding `--package` as argument to `cargo release` still creates version tags in the form of `vx.y.z`
tag-prefix = ""

[workspace.dependencies]
arbitrary = "1.3.2"
libfuzzer-sys = "0.4"
stacker = "0.1.15"
doc-comment = "0.3.3"
base64 = "0.21.1"
zeroize = "1.7.0"
memoffset = "0.9.0"
lazy_static = "1.4.0"
thiserror = "1.0.40"
paste = "1.0.12"
env_logger = "0.10.0"
serde = "1.0.163"
toml = "0.7.4"
mio = "0.8.6"
clap = "4.3.0"
static_assertions = "1.1.0"
log = { version = "0.4.17" }
anyhow = { version = "1.0.71" }
libsodium-sys-stable= { version = "1.19.28" }
oqs-sys = {default-features = false, version = "0.8" }