[package]
name = "rosenpass-sodium"
authors = ["Karolin Varner <karo@cupdev.net>", "wucke13 <wucke13@gmail.com>"]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Rosenpass internal bindings to libsodium"
homepage = "https://rosenpass.eu/"
repository = "https://github.com/rosenpass/rosenpass"
readme = "readme.md"

[dependencies]
rosenpass-util = { path = "../util" }
rosenpass-to = { path = "../to" }
anyhow = { workspace = true, features = ["backtrace"] }
libsodium-sys-stable = { workspace = true, features = ["use-pkg-config"] }
log = { workspace = true }
