[package]
name = "rosenpass"
version = "0.2.1"
authors = ["Karolin Varner <karo@cupdev.net>", "wucke13 <wucke13@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Build post-quantum-secure VPNs with WireGuard!"
homepage = "https://rosenpass.eu/"
repository = "https://github.com/rosenpass/rosenpass"
readme = "readme.md"

[[bench]]
name = "handshake"
harness = false

[dependencies]
rosenpass-util = { path = "../util" }
rosenpass-constant-time = { path = "../constant-time" }
rosenpass-sodium = { path = "../sodium" }
rosenpass-ciphers = { path = "../ciphers" }
rosenpass-to = { path = "../to" }
anyhow = { workspace = true }
static_assertions = { workspace = true }
memoffset = { workspace = true }
libsodium-sys-stable = { workspace = true }
oqs-sys = { workspace = true }
lazy_static = { workspace = true }
thiserror = { workspace = true }
paste = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
clap = { workspace = true }
mio = { workspace = true }

[build-dependencies]
anyhow = { workspace = true }

[dev-dependencies]
criterion = "0.4.0"
test_bin = "0.4.0"
stacker = { workspace = true }
